from __future__ import annotations

import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from fastapi import APIRouter, Depends, Header, HTTPException
from pydantic import BaseModel, Field

from app import db
from app.config import get_settings

router = APIRouter(prefix='/rwa-mine', tags=['RWA Mine Project Scaffold Generator'])


def require_key(x_hermes_api_key: str = Header(default='')) -> None:
    settings = get_settings()
    if settings.hermes_agent_api_key and x_hermes_api_key != settings.hermes_agent_api_key:
        raise HTTPException(status_code=401, detail='Invalid API key')


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def safe_name(value: str) -> str:
    name = re.sub(r'[^a-zA-Z0-9_-]+', '-', value.strip()).strip('-').lower()
    if not name:
        raise ValueError('project_name is empty')
    return name[:80]


class ScaffoldRequest(BaseModel):
    project_name: str = Field(default='rwa-mine-mvp', min_length=2)
    overwrite: bool = False
    include_frontend: bool = True
    include_contracts: bool = True
    include_backend: bool = True
    include_infra: bool = True
    include_docs: bool = True


def scaffold_root() -> Path:
    return Path('/app/storage/rwa_mine_projects')


def write(path: Path, content: str) -> Dict[str, Any]:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + '\n', encoding='utf-8')
    return {'path': str(path), 'size': path.stat().st_size}


def ensure_tables() -> None:
    with db.connect() as conn:
        conn.execute('''CREATE TABLE IF NOT EXISTS rwa_mine_scaffolds (id INTEGER PRIMARY KEY AUTOINCREMENT,project_name TEXT NOT NULL,root_path TEXT NOT NULL,file_count INTEGER NOT NULL,manifest_json TEXT NOT NULL,created_at TEXT NOT NULL)''')


README = r"""
# RWA Mine MVP

This scaffold is generated by Hermes RWA Mine MVP Command Center.

## MVP Scope
- Wallet connect
- Daily activation mining
- Staking vault and sRWAU
- L1 referral rewards
- Node NFT minting
- Treasury / buyback / burn dashboard
- Static RWA asset showcase only in MVP v1

## Security Boundary
- No private keys in repository
- Treasury / Proxy Admin / parameter permissions must be owned by Gnosis Safe 3/5
- Real RWA asset pool is not connected in MVP v1
- External audit is required before mainnet launch
"""

FRONTEND_PACKAGE = r"""
{
  "name": "rwa-mine-frontend",
  "private": true,
  "scripts": {"dev": "next dev", "build": "next build", "start": "next start", "lint": "next lint"},
  "dependencies": {"@rainbow-me/rainbowkit": "latest", "wagmi": "latest", "viem": "latest", "next": "latest", "react": "latest", "react-dom": "latest", "echarts": "latest", "echarts-for-react": "latest"},
  "devDependencies": {"typescript": "latest", "tailwindcss": "latest", "eslint": "latest"}
}
"""

FRONTEND_PAGE = r"""
export default function Page() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-4xl font-bold">RWA Mine MVP</h1>
      <p className="mt-3 text-gray-500">Wallet → Daily Mining → Stake → Referral → Node → Dashboard</p>
      <section className="grid grid-cols-1 md:grid-cols-4 gap-4 mt-8">
        {['TVL','Burned RWAU','Network Hashrate','Node Seats'].map(x => <div key={x} className="rounded-xl border p-5"><b>{x}</b><p>--</p></div>)}
      </section>
    </main>
  )
}
"""

WALLET_TS = r"""
import { getDefaultConfig } from '@rainbow-me/rainbowkit'
import { mainnet, polygon, bsc } from 'wagmi/chains'

export const walletConfig = getDefaultConfig({
  appName: 'RWA Mine',
  projectId: process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || '',
  chains: [mainnet, polygon, bsc],
  ssr: true,
})
"""

SOL_RWAU = r"""
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

contract RWAUToken is ERC20, AccessControl {
    bytes32 public constant TREASURY_ROLE = keccak256("TREASURY_ROLE");
    uint256 public constant MAX_TAX_BPS = 500;
    uint256 public buyTaxBps;
    uint256 public sellTaxBps;
    mapping(address => bool) public blacklist;

    constructor(address admin) ERC20("RWA Mine Token", "RWAU") {
        _grantRole(DEFAULT_ADMIN_ROLE, admin);
        _grantRole(TREASURY_ROLE, admin);
    }

    function setTax(uint256 buyBps, uint256 sellBps) external onlyRole(DEFAULT_ADMIN_ROLE) {
        require(buyBps <= MAX_TAX_BPS && sellBps <= MAX_TAX_BPS, "tax too high");
        buyTaxBps = buyBps;
        sellTaxBps = sellBps;
    }

    function setBlacklist(address account, bool value) external onlyRole(DEFAULT_ADMIN_ROLE) {
        blacklist[account] = value;
    }

    function burn(uint256 amount) external {
        _burn(msg.sender, amount);
    }

    function _update(address from, address to, uint256 value) internal override {
        require(!blacklist[from] && !blacklist[to], "blacklisted");
        super._update(from, to, value);
    }
}
"""

SOL_SRWAU = r"""
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

contract sRWAUToken is ERC20, AccessControl {
    bytes32 public constant VAULT_ROLE = keccak256("VAULT_ROLE");

    constructor(address admin) ERC20("Staked RWAU", "sRWAU") {
        _grantRole(DEFAULT_ADMIN_ROLE, admin);
    }

    function mint(address to, uint256 amount) external onlyRole(VAULT_ROLE) { _mint(to, amount); }
    function burn(address from, uint256 amount) external onlyRole(VAULT_ROLE) { _burn(from, amount); }

    function _update(address from, address to, uint256 value) internal override {
        require(from == address(0) || to == address(0), "sRWAU non-transferable");
        super._update(from, to, value);
    }
}
"""

SOL_STAKING = r"""
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

contract StakingVault {
    struct StakeOrder { address user; uint256 amount; uint64 start; uint64 end; uint16 penaltyBps; bool closed; }
    mapping(uint256 => StakeOrder) public orders;
    uint256 public nextOrderId;

    event Staked(uint256 indexed orderId, address indexed user, uint256 amount, uint64 end);
    event Unstaked(uint256 indexed orderId, address indexed user, uint256 amount, uint256 penalty);

    function stake(uint256 amount, uint64 lockDays) external returns (uint256 orderId) {
        require(lockDays == 30 || lockDays == 90 || lockDays == 180 || lockDays == 365, "invalid tier");
        orderId = ++nextOrderId;
        orders[orderId] = StakeOrder(msg.sender, amount, uint64(block.timestamp), uint64(block.timestamp + lockDays * 1 days), 1000, false);
        emit Staked(orderId, msg.sender, amount, orders[orderId].end);
    }
}
"""

CONTRACTS_PACKAGE = r"""
{
  "name": "rwa-mine-contracts",
  "private": true,
  "scripts": {"test": "hardhat test", "compile": "hardhat compile", "coverage": "solidity-coverage"},
  "devDependencies": {"hardhat": "latest", "@nomicfoundation/hardhat-toolbox": "latest", "@openzeppelin/contracts": "latest", "solidity-coverage": "latest", "typescript": "latest"}
}
"""

HARDHAT = r"""
import { HardhatUserConfig } from 'hardhat/config'
import '@nomicfoundation/hardhat-toolbox'

const config: HardhatUserConfig = {
  solidity: { version: '0.8.24', settings: { optimizer: { enabled: true, runs: 200 } } },
  networks: { hardhat: {} }
}
export default config
"""

BACKEND_PACKAGE = r"""
{
  "name": "rwa-mine-backend",
  "private": true,
  "scripts": {"start:dev": "nest start --watch", "build": "nest build", "test": "jest"},
  "dependencies": {"@nestjs/common": "latest", "@nestjs/core": "latest", "@nestjs/platform-express": "latest", "@prisma/client": "latest", "bullmq": "latest", "ioredis": "latest"},
  "devDependencies": {"@nestjs/cli": "latest", "typescript": "latest", "prisma": "latest", "jest": "latest"}
}
"""

NEST_MAIN = r"""
import { NestFactory } from '@nestjs/core'
import { AppModule } from './app.module'

async function bootstrap() {
  const app = await NestFactory.create(AppModule)
  app.enableCors()
  await app.listen(process.env.PORT || 3001)
}
bootstrap()
"""

APP_MODULE = r"""
import { Module } from '@nestjs/common'

@Module({ imports: [], controllers: [], providers: [] })
export class AppModule {}
"""

PRISMA_SCHEMA = r"""
generator client { provider = "prisma-client-js" }
datasource db { provider = "postgresql" url = env("DATABASE_URL") }

model User { id String @id @default(cuid()) wallet String @unique riskScore Int @default(0) createdAt DateTime @default(now()) }
model WalletBinding { id String @id @default(cuid()) userId String chain String address String verifiedAt DateTime? }
model DailyMiningLog { id String @id @default(cuid()) userId String date DateTime hashrate Decimal emission Decimal claimed Boolean @default(false) }
model StakeOrder { id String @id @default(cuid()) userId String tier String amount Decimal start DateTime end DateTime penaltyRate Int }
model RewardClaim { id String @id @default(cuid()) userId String type String amount Decimal txHash String? claimedAt DateTime @default(now()) }
model ReferralRelation { id String @id @default(cuid()) userId String l1 String? l2 String? l3 String? boundAt DateTime @default(now()) }
model TeamStatsDaily { id String @id @default(cuid()) userId String date DateTime directCount Int activeCount Int teamHashrate Decimal }
model NodeOrder { id String @id @default(cuid()) userId String tier String tokenId String? costBurned Decimal mintedAt DateTime @default(now()) }
model BurnRecord { id String @id @default(cuid()) source String amount Decimal txHash String burnedAt DateTime @default(now()) }
model BuybackRecord { id String @id @default(cuid()) usdtAmount Decimal rwauAmount Decimal price Decimal burned Decimal injected Decimal at DateTime @default(now()) }
model AssetPool { id String @id @default(cuid()) name String type String size Decimal apyMin Decimal apyMax Decimal term String status String }
model SystemConfig { key String @id value String updatedAt DateTime @updatedAt }
"""

DOCKER_COMPOSE = r"""
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: rwa
      POSTGRES_PASSWORD: rwa_dev_only
      POSTGRES_DB: rwa_mine
    ports: ['5432:5432']
  redis:
    image: redis:7
    ports: ['6379:6379']
"""

SECURITY_MD = r"""
# Security Requirements

- Gnosis Safe 3/5 controls Treasury, Proxy Admin, tax parameters and blacklist.
- Contract coverage must be greater than 90%.
- Testnet must run for 30 days before mainnet.
- External audit must be completed before launch.
- MVP v1 cannot claim real RWA yield, guaranteed return, or principal protection.
"""

GATE_MD = r"""
# Launch Gate Check

- [ ] P0 frontend complete
- [ ] P0 contracts complete
- [ ] P0 backend complete
- [ ] Test coverage > 90%
- [ ] 30-day testnet run complete
- [ ] External audit complete
- [ ] Gnosis Safe 3/5 configured
- [ ] Treasury and Proxy Admin owned by Safe
- [ ] Static RWA asset language reviewed
- [ ] Rollback plan ready
"""


def generate_files(root: Path, req: ScaffoldRequest) -> List[Dict[str, Any]]:
    files: List[Dict[str, Any]] = []
    files.append(write(root / 'README.md', README))
    if req.include_frontend:
        files += [
            write(root / 'frontend/package.json', FRONTEND_PACKAGE),
            write(root / 'frontend/app/page.tsx', FRONTEND_PAGE),
            write(root / 'frontend/app/mine/page.tsx', FRONTEND_PAGE.replace('RWA Mine MVP', 'Daily Mining')),
            write(root / 'frontend/app/stake/page.tsx', FRONTEND_PAGE.replace('RWA Mine MVP', 'Staking Vault')),
            write(root / 'frontend/app/node/page.tsx', FRONTEND_PAGE.replace('RWA Mine MVP', 'Node NFT')),
            write(root / 'frontend/app/referral/page.tsx', FRONTEND_PAGE.replace('RWA Mine MVP', 'Referral Center')),
            write(root / 'frontend/app/profile/page.tsx', FRONTEND_PAGE.replace('RWA Mine MVP', 'Profile Center')),
            write(root / 'frontend/app/assets/page.tsx', FRONTEND_PAGE.replace('RWA Mine MVP', 'Static RWA Asset Showcase')),
            write(root / 'frontend/lib/wallet.ts', WALLET_TS),
            write(root / 'frontend/.env.example', 'NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=\nNEXT_PUBLIC_API_BASE=http://localhost:3001'),
        ]
    if req.include_contracts:
        files += [
            write(root / 'contracts/package.json', CONTRACTS_PACKAGE),
            write(root / 'contracts/hardhat.config.ts', HARDHAT),
            write(root / 'contracts/contracts/RWAUToken.sol', SOL_RWAU),
            write(root / 'contracts/contracts/sRWAUToken.sol', SOL_SRWAU),
            write(root / 'contracts/contracts/StakingVault.sol', SOL_STAKING),
            write(root / 'contracts/contracts/RewardDistributor.sol', '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.24;\ncontract RewardDistributor {}'),
            write(root / 'contracts/contracts/ReferralRegistry.sol', '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.24;\ncontract ReferralRegistry {}'),
            write(root / 'contracts/contracts/NodeNFT.sol', '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.24;\ncontract NodeNFT {}'),
            write(root / 'contracts/contracts/Treasury.sol', '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.24;\ncontract Treasury {}'),
            write(root / 'contracts/scripts/deploy.ts', 'async function main(){ console.log("deploy RWA Mine contracts") }\nmain()'),
            write(root / 'contracts/test/RWAUToken.test.ts', 'describe("RWAUToken", function(){ it("placeholder", async function(){}) })'),
        ]
    if req.include_backend:
        files += [
            write(root / 'backend/package.json', BACKEND_PACKAGE),
            write(root / 'backend/src/main.ts', NEST_MAIN),
            write(root / 'backend/src/app.module.ts', APP_MODULE),
            write(root / 'backend/prisma/schema.prisma', PRISMA_SCHEMA),
            write(root / 'backend/.env.example', 'DATABASE_URL=postgresql://rwa:rwa_dev_only@localhost:5432/rwa_mine\nREDIS_URL=redis://localhost:6379'),
            write(root / 'backend/src/modules/mining/README.md', '# MiningModule\nDaily activation and emission APIs.'),
            write(root / 'backend/src/modules/staking/README.md', '# StakingModule\nStake orders, rewards and unlock APIs.'),
            write(root / 'backend/src/modules/referral/README.md', '# ReferralModule\nL1 referral relation and stats APIs.'),
            write(root / 'backend/src/modules/dashboard/README.md', '# DashboardModule\nTVL, burn, buyback and hashrate APIs.'),
            write(root / 'backend/src/modules/risk/README.md', '# RiskModule\nAnti-sybil, frequency limit and anomaly checks.'),
        ]
    if req.include_infra:
        files += [
            write(root / 'infra/docker-compose.yml', DOCKER_COMPOSE),
            write(root / 'infra/.env.example', 'POSTGRES_PASSWORD=rwa_dev_only\nREDIS_URL=redis://redis:6379'),
        ]
    if req.include_docs:
        files += [
            write(root / 'docs/SECURITY.md', SECURITY_MD),
            write(root / 'docs/LAUNCH_GATE_CHECK.md', GATE_MD),
            write(root / 'docs/API_MODULES.md', '# API Modules\nUserModule / MiningModule / StakingModule / ReferralModule / NodeModule / DashboardModule / RiskModule'),
            write(root / 'docs/COMPLIANCE_LANGUAGE.md', '# Compliance Language\nMVP v1 uses static RWA asset showcase only. Do not claim guaranteed yield or principal protection.'),
        ]
    return files


@router.post('/scaffold/generate', dependencies=[Depends(require_key)])
def generate_scaffold(req: ScaffoldRequest) -> Dict[str, Any]:
    ensure_tables()
    try:
        project = safe_name(req.project_name)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    root = scaffold_root() / project
    if root.exists():
        if not req.overwrite:
            raise HTTPException(status_code=400, detail='project already exists; set overwrite=true')
        shutil.rmtree(root)
    root.mkdir(parents=True, exist_ok=True)
    files = generate_files(root, req)
    manifest = {'project_name': project, 'root_path': str(root), 'file_count': len(files), 'files': files, 'created_at': now()}
    with db.connect() as conn:
        conn.execute('INSERT INTO rwa_mine_scaffolds (project_name, root_path, file_count, manifest_json, created_at) VALUES (?, ?, ?, ?, ?)', (project, str(root), len(files), json.dumps(manifest, ensure_ascii=False), now()))
    db.audit('rwa_mine_scaffold_generate', 'rwa_mine_scaffold', project, {'file_count': len(files), 'root_path': str(root)}, 'success', 'medium', 'not_required')
    return {'status': 'success', 'manifest': manifest}


@router.get('/scaffold/list')
def list_scaffolds() -> List[Dict[str, Any]]:
    ensure_tables()
    with db.connect() as conn:
        return [dict(r) for r in conn.execute('SELECT id, project_name, root_path, file_count, created_at FROM rwa_mine_scaffolds ORDER BY id DESC LIMIT 100').fetchall()]


@router.get('/scaffold/latest')
def latest_scaffold() -> Dict[str, Any]:
    ensure_tables()
    with db.connect() as conn:
        r = conn.execute('SELECT * FROM rwa_mine_scaffolds ORDER BY id DESC LIMIT 1').fetchone()
    if not r:
        raise HTTPException(status_code=404, detail='no scaffold found')
    data = dict(r)
    data['manifest'] = json.loads(data.pop('manifest_json'))
    return data
